[tox]
envlist=pytest-check,verify-tc-requirement-polarion,code-check,verify-bugs-are-open,unused-code,verify-jira-tickets-are-open
skipsdist=True

[testenv:code-check]
basepython = python3
recreate=True
setenv =
    PYTHONPATH = {toxinidir}
deps=
    pre-commit
    gitlint
commands =
    pip install pip --upgrade
    pip install tox --upgrade
    pre-commit clean
    pre-commit run --all-files
    gitlint

[testenv:pytest-check]
basepython = python3
recreate=True
setenv =
    PYTHONPATH = {toxinidir}
    LC_ALL = en_US.utf8
    LANG = en_US.utf8
deps=
    poetry
commands =
    pip install pip --upgrade
    pip install pycurl --no-cache-dir --ignore-install
    pip install tox --upgrade
    poetry install
    poetry export --without-hashes -n
    poetry run pytest --collect-only
    poetry run pytest --upgrade=cnv --cnv-image=NA --cnv-version=NA --collect-only
    poetry run pytest --upgrade=ocp --ocp-image=NA --collect-only
    poetry run pytest --tc-file=tests/global_config_ci.py --collect-only
    poetry run pytest --tc-file=tests/global_config_interop.py --collect-only
    poetry run pytest --tc-file=tests/global_config.py -m smoke --collect-only
    poetry run pytest --tc-file=tests/global_config_upstream.py --collect-only
    poetry run pytest --tc-file=tests/global_config.py --tc-format=python --setup-plan


# Polarion
# Should run on every commit.
[testenv:verify-tc-requirement-polarion]
basepython = python3
recreate=True
setenv =
    PYTHONPATH = {toxinidir}
commands =
    pip install pip --upgrade
    pip install tox --upgrade
    pip install git+https://github.com/RedHatQE/pylero.git
    python3 scripts/polarion/polarion_verify_tc_requirement.py

# Should run only after merged.
[testenv:mark-automated-polarion]
basepython = python3
recreate=True
setenv =
    PYTHONPATH = {toxinidir}
commands =
    pip install pip --upgrade
    pip install tox --upgrade
    pip install git+https://github.com/RedHatQE/pylero.git
    python3 scripts/polarion/polarion_set_automated.py


# Should run only after merged.
[testenv:close-jira-tickets-by-commit-msg]
basepython = python3
recreate=True
setenv =
    PYTHONPATH = {toxinidir}
commands =
    pip install pip --upgrade
    pip install tox --upgrade
    pip install jira
    python3 scripts/jira/close_jira_on_merge.py

#Bugzilla
[testenv:verify-bugs-are-open]
basepython = python3
recreate=True
setenv =
    PYTHONPATH = {toxinidir}
deps:
    python-bugzilla
    GitPython

commands =
    pip install pip --upgrade
    pip install tox --upgrade
    python3 scripts/bugzilla/check_bug_status_closed.py

#Jira
[testenv:verify-jira-tickets-are-open]
basepython = python3
recreate=True
setenv =
    PYTHONPATH = {toxinidir}
deps:
    jira

commands =
    pip install pip --upgrade
    pip install tox --upgrade
    python3 scripts/jira/check_jira_status_closed.py


#Unused code
[testenv:unused-code]
basepython = python3
recreate=True
setenv =
    PYTHONPATH = {toxinidir}
deps:
    pygerrit2
    GitPython
commands =
    pip install pip --upgrade
    pip install tox --upgrade
    python3 scripts/code_check/unused_code.py
