[tox]
envlist=pytest-check,unused-code
skipsdist=True

[testenv:pytest-check]
basepython = python3
recreate=True
setenv =
    PYTHONPATH = {toxinidir}
    LC_ALL = en_US.utf8
    LANG = en_US.utf8
deps=
    poetry
commands =
    pip install pip --upgrade
    pip install tox --upgrade
    poetry install
    poetry export --without-hashes -n
    poetry run pytest --collect-only
    poetry run pytest --upgrade=cnv --cnv-image=NA --cnv-version=NA --collect-only
    poetry run pytest --upgrade=ocp --ocp-image=NA --collect-only
    poetry run pytest --tc-file=tests/global_config_aws.py --collect-only
    poetry run pytest --tc-file=tests/global_config_rh_it.py --collect-only
    poetry run pytest --tc-file=tests/global_config.py -m smoke --collect-only
    poetry run pytest --tc-file=tests/global_config.py --tc-format=python --setup-plan


# Polarion
# Should run on every commit.
[testenv:verify-tc-requirement-polarion]
basepython = python3
recreate=True
setenv =
    PYTHONPATH = {toxinidir}
deps:
    python-utility-scripts
commands =
    pip install pip --upgrade
    pip install tox --upgrade
    pyutils-polarion-verify-tc-requirements --project-id "CNV" --branch "origin/cnv-4.12" --verbose

# Should run only after merged.
[testenv:mark-automated-polarion]
basepython = python3
recreate=True
setenv =
    PYTHONPATH = {toxinidir}
deps:
    python-utility-scripts
commands =
    pip install pip --upgrade
    pip install tox --upgrade
    pyutils-polarion-set-automated --project-id "CNV" --branch "origin/cnv-4.12" --verbose


#Jira
[testenv:verify-bugs-are-open]
basepython = python3
recreate=True
setenv =
    PYTHONPATH = {toxinidir}
deps:
    GitPython
    jira

commands =
    pip install pip --upgrade
    pip install tox --upgrade
    python3 scripts/jira/check_bug_status_closed.py

#Unused code
[testenv:unused-code]
basepython = python3
recreate=True
setenv =
    PYTHONPATH = {toxinidir}
deps:
    python-utility-scripts
commands =
    pip install pip --upgrade
    pip install tox --upgrade
    pyutils-unusedcode --exclude-files "pytest_matrix_utils.py" --exclude-function-prefixes "pytest_"
