[tox]
envlist=pytest-check,unused-code
skipsdist=True

[testenv]
basepython = python3

[testenv:pytest-check]
recreate=True
setenv =
    PYTHONPATH = {toxinidir}
    LC_ALL = en_US.utf8
    LANG = en_US.utf8
deps=
    poetry
commands =
    poetry env use python3.12
    poetry install
    poetry run pytest --collect-only
    poetry run pytest --upgrade=cnv --cnv-image=NA --cnv-version=NA --collect-only
    poetry run pytest --upgrade=ocp --ocp-image=NA --collect-only
    poetry run pytest --tc-file=tests/global_config_rh_it.py --collect-only
    poetry run pytest --tc-file=tests/global_config.py -m smoke --collect-only
    poetry run pytest --tc-file=tests/global_config.py --tc-format=python --setup-plan


# Polarion
# Should run on every commit.
[testenv:verify-tc-requirement-polarion]
recreate=True
setenv =
    PYTHONPATH = {toxinidir}
deps:
    python-utility-scripts
commands =
    pip install pip --upgrade
    pip install tox --upgrade
    pyutils-polarion-verify-tc-requirements --project-id "CNV" --branch "origin/cnv-4.12" --verbose

# Should run only after merged.
[testenv:mark-automated-polarion]
recreate=True
setenv =
    PYTHONPATH = {toxinidir}
deps:
    python-utility-scripts >= 1.0.15
commands =
    pip install pip --upgrade
    pip install tox --upgrade
    pyutils-polarion-set-automated --project-id "CNV" {posargs}


# TODO: remove once verify-bugs-are-open-gh is checked and works properly
#Jira
[testenv:verify-bugs-are-open]
recreate=True
setenv =
    PYTHONPATH = {toxinidir}
deps:
    python-utility-scripts

commands =
    pip install pip --upgrade
    pip install tox --upgrade
    pyutils-jira --config-file-path jira.cfg --target-versions "4.12.17,4.12.18,4.12.19,4.12.20" --verbose

[testenv:verify-bugs-are-open-gh]
recreate=True
passenv = JIRA_TOKEN
deps =
    python-utility-scripts
commands =
    pyutils-jira --url https://issues.redhat.com --target-versions "4.12.0,4.12.z" --resolved-statuses "verified,release pending,closed" --issue-pattern "([A-Z]+-[0-9]+)" --verbose

#Unused code
[testenv:unused-code]
recreate=True
setenv =
    PYTHONPATH = {toxinidir}
deps:
    python-utility-scripts
commands =
    pip install pip --upgrade
    pip install tox --upgrade
    pyutils-unusedcode --exclude-files "pytest_matrix_utils.py" --exclude-function-prefixes "pytest_"
