from ocp_resources.resource import Resource

from utilities.constants import (
    CDI_APISERVER,
    CDI_DEPLOYMENT,
    CDI_KUBEVIRT_HYPERCONVERGED,
    CDI_OPERATOR,
    CDI_UPLOADPROXY,
    CLUSTER,
    CLUSTER_NETWORK_ADDONS_OPERATOR,
    CNAO_OPERATOR,
    CREATING_VIRTUAL_MACHINE,
    GRAFANA_DASHBOARD_KUBEVIRT_TOP_CONSUMERS,
    HCO_OPERATOR,
    HCO_PART_OF_LABEL_VALUE,
    HCO_WEBHOOK,
    HOSTPATH_PROVISIONER_OPERATOR,
    HPP_POOL,
    HYPERCONVERGED_CLUSTER,
    HYPERCONVERGED_CLUSTER_CLI_DOWNLOAD,
    HYPERCONVERGED_CLUSTER_OPERATOR_METRICS,
    KUBEMACPOOL_CERT_MANAGER,
    KUBEMACPOOL_MAC_CONTROLLER_MANAGER,
    KUBEVIRT_CLUSTER_CRITICAL,
    KUBEVIRT_HYPERCONVERGED_OPERATOR_METRICS,
    KUBEVIRT_HYPERCONVERGED_PROMETHEUS_RULE,
    KUBEVIRT_KUBEVIRT_HYPERCONVERGED,
    KUBEVIRT_PLUGIN,
    KUBEVIRT_PLUGIN_SERVICE,
    MANAGED_BY_LABEL_VALUE_OLM,
    NGINX_CONF,
    RHEL8_GUEST,
    RHEL9_GUEST,
    SSP_KUBEVIRT_HYPERCONVERGED,
    SSP_OPERATOR,
    TEKTON_TASK_OPERATOR,
    TTO_KUBEVIRT_HYPERCONVERGED,
    UPLOAD_BOOT_SOURCE,
    VIRT_API,
    VIRT_CONTROLLER,
    VIRT_EXPORTPROXY,
    VIRT_OPERATOR,
    VIRT_TEMPLATE_VALIDATOR,
    VIRTCTL_CLIDOWNLOADS_KUBEVIRT_HYPERCONVERGED,
    VIRTIO_WIN,
)


VIRITO_WIN_STORAGE = "virtio-win-storage"
# components
TEMPLATING_STR = "templating"
DEPLOYMENT_STR = "deployment"
MONITORING_STR = "monitoring"
SCHEDULE_STR = "schedule"
COMPUTE_STR = "compute"
IMPORT_STR = "import"
STORAGE_STR = "storage"
NETWORK_STR = "network"
TEKTON_STR = "tekton"
# labels keys
MANAGED_BY_LABEL_KEY = f"{Resource.ApiGroup.APP_KUBERNETES_IO}/managed-by"
VERSION_LABEL_KEY = f"{Resource.ApiGroup.APP_KUBERNETES_IO}/version"
COMPONENT_LABEL_KEY = f"{Resource.ApiGroup.APP_KUBERNETES_IO}/component"
PART_OF_LABEL_KEY = f"{Resource.ApiGroup.APP_KUBERNETES_IO}/part-of"
ALL_LABEL_KEYS = [
    MANAGED_BY_LABEL_KEY,
    VERSION_LABEL_KEY,
    COMPONENT_LABEL_KEY,
    PART_OF_LABEL_KEY,
]
# Deployment expected labels
EXPECTED_COMPONENT_LABELS_DICT_MAP = {
    CDI_APISERVER: {
        MANAGED_BY_LABEL_KEY: CDI_OPERATOR,
        COMPONENT_LABEL_KEY: STORAGE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    HPP_POOL: {
        MANAGED_BY_LABEL_KEY: HOSTPATH_PROVISIONER_OPERATOR,
        COMPONENT_LABEL_KEY: STORAGE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    CDI_DEPLOYMENT: {
        MANAGED_BY_LABEL_KEY: CDI_OPERATOR,
        COMPONENT_LABEL_KEY: STORAGE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    CDI_OPERATOR: {
        MANAGED_BY_LABEL_KEY: MANAGED_BY_LABEL_VALUE_OLM,
        COMPONENT_LABEL_KEY: STORAGE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    CDI_UPLOADPROXY: {
        MANAGED_BY_LABEL_KEY: CDI_OPERATOR,
        COMPONENT_LABEL_KEY: STORAGE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    CLUSTER_NETWORK_ADDONS_OPERATOR: {
        MANAGED_BY_LABEL_KEY: MANAGED_BY_LABEL_VALUE_OLM,
        COMPONENT_LABEL_KEY: NETWORK_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    HCO_OPERATOR: {
        MANAGED_BY_LABEL_KEY: MANAGED_BY_LABEL_VALUE_OLM,
        COMPONENT_LABEL_KEY: DEPLOYMENT_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    HCO_WEBHOOK: {
        MANAGED_BY_LABEL_KEY: MANAGED_BY_LABEL_VALUE_OLM,
        COMPONENT_LABEL_KEY: DEPLOYMENT_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    HOSTPATH_PROVISIONER_OPERATOR: {
        MANAGED_BY_LABEL_KEY: MANAGED_BY_LABEL_VALUE_OLM,
        COMPONENT_LABEL_KEY: STORAGE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    SSP_OPERATOR: {
        MANAGED_BY_LABEL_KEY: MANAGED_BY_LABEL_VALUE_OLM,
        COMPONENT_LABEL_KEY: SCHEDULE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    VIRT_OPERATOR: {
        MANAGED_BY_LABEL_KEY: MANAGED_BY_LABEL_VALUE_OLM,
        COMPONENT_LABEL_KEY: COMPUTE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    HYPERCONVERGED_CLUSTER_CLI_DOWNLOAD: {
        MANAGED_BY_LABEL_KEY: MANAGED_BY_LABEL_VALUE_OLM,
        COMPONENT_LABEL_KEY: DEPLOYMENT_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    TEKTON_TASK_OPERATOR: {
        MANAGED_BY_LABEL_KEY: MANAGED_BY_LABEL_VALUE_OLM,
        COMPONENT_LABEL_KEY: TEKTON_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    VIRT_EXPORTPROXY: {
        MANAGED_BY_LABEL_KEY: VIRT_OPERATOR,
        COMPONENT_LABEL_KEY: COMPUTE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    KUBEMACPOOL_CERT_MANAGER: {
        MANAGED_BY_LABEL_KEY: CNAO_OPERATOR,
        COMPONENT_LABEL_KEY: NETWORK_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    KUBEMACPOOL_MAC_CONTROLLER_MANAGER: {
        MANAGED_BY_LABEL_KEY: CNAO_OPERATOR,
        COMPONENT_LABEL_KEY: NETWORK_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    KUBEVIRT_PLUGIN: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: DEPLOYMENT_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    VIRT_API: {
        MANAGED_BY_LABEL_KEY: VIRT_OPERATOR,
        COMPONENT_LABEL_KEY: COMPUTE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    VIRT_CONTROLLER: {
        MANAGED_BY_LABEL_KEY: VIRT_OPERATOR,
        COMPONENT_LABEL_KEY: COMPUTE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    VIRT_TEMPLATE_VALIDATOR: {
        MANAGED_BY_LABEL_KEY: SSP_OPERATOR,
        COMPONENT_LABEL_KEY: TEMPLATING_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
}
EXPECTED_RELATED_OBJECTS_LABELS_DICT_MAP = {
    KUBEVIRT_HYPERCONVERGED_PROMETHEUS_RULE: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: MONITORING_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HYPERCONVERGED_CLUSTER,
    },
    HYPERCONVERGED_CLUSTER_OPERATOR_METRICS: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: MONITORING_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HYPERCONVERGED_CLUSTER,
    },
    KUBEVIRT_HYPERCONVERGED_OPERATOR_METRICS: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: MONITORING_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HYPERCONVERGED_CLUSTER,
    },
    KUBEVIRT_CLUSTER_CRITICAL: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: COMPUTE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HYPERCONVERGED_CLUSTER,
    },
    KUBEVIRT_KUBEVIRT_HYPERCONVERGED: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: COMPUTE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HYPERCONVERGED_CLUSTER,
    },
    CDI_KUBEVIRT_HYPERCONVERGED: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: STORAGE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HYPERCONVERGED_CLUSTER,
    },
    CLUSTER: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: NETWORK_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HYPERCONVERGED_CLUSTER,
    },
    SSP_KUBEVIRT_HYPERCONVERGED: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: SCHEDULE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HYPERCONVERGED_CLUSTER,
    },
    TTO_KUBEVIRT_HYPERCONVERGED: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: TEKTON_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HYPERCONVERGED_CLUSTER,
    },
    VIRTCTL_CLIDOWNLOADS_KUBEVIRT_HYPERCONVERGED: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: COMPUTE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HYPERCONVERGED_CLUSTER,
    },
    HYPERCONVERGED_CLUSTER_CLI_DOWNLOAD: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: COMPUTE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HYPERCONVERGED_CLUSTER,
    },
    KUBEVIRT_PLUGIN_SERVICE: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: DEPLOYMENT_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HYPERCONVERGED_CLUSTER,
    },
    CREATING_VIRTUAL_MACHINE: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: COMPUTE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HYPERCONVERGED_CLUSTER,
    },
    UPLOAD_BOOT_SOURCE: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: COMPUTE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HYPERCONVERGED_CLUSTER,
    },
    GRAFANA_DASHBOARD_KUBEVIRT_TOP_CONSUMERS: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: COMPUTE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HYPERCONVERGED_CLUSTER,
    },
    RHEL8_GUEST: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: COMPUTE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HYPERCONVERGED_CLUSTER,
    },
    RHEL9_GUEST: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: COMPUTE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HYPERCONVERGED_CLUSTER,
    },
    VIRTIO_WIN: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: DEPLOYMENT_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HYPERCONVERGED_CLUSTER,
    },
    VIRITO_WIN_STORAGE: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: STORAGE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HYPERCONVERGED_CLUSTER,
    },
    KUBEVIRT_PLUGIN: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: DEPLOYMENT_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HYPERCONVERGED_CLUSTER,
    },
    NGINX_CONF: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: DEPLOYMENT_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HYPERCONVERGED_CLUSTER,
    },
}
