FROM centos:7

RUN yum install epel-release -y && yum update -y && yum install iproute tcpdump openvswitch qemu-img NetworkManager xfreerdp xauth xorg-x11-server-Xvfb which nftables stress-ng -y && yum clean all
