name: Jira validation

on:
  push:


jobs:
  verify-jira:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Add Config File to current folder
        run: |
          echo "$CONFIG_CONTENT" > jira.cfg
        env:
          CONFIG_CONTENT: ${{ secrets.JIRA_CFG }}
